apiVersion: v1
kind: Service
metadata:
  name: go-app-service
spec:
  selector:
    app: go-app
  type: ClusterIP  # Или LoadBalancer, если пробрасываешь порт
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
