apiVersion: apps/v1
kind: Deployment
metadata:
  name: tstkuber
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tstkuber
  template:
    metadata:
      labels:
        app: tstkuber
    spec:
      containers:
        - name: tstkuber
          image: DOCKER_USERNAME/tstkuber:latest
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: tstkuber-service
spec:
  selector:
    app: tstkuber
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
      nodePort: 30080
  type: NodePort



#apiVersion: apps/v1
#kind: Deployment
#metadata:
#  name: tstkuber
#spec:
#  replicas: 1
#  selector:
#    matchLabels:
#      app: tstkuber
#  template:
#    metadata:
#      labels:
#        app: tstkuber
#    spec:
#      containers:
#        - name: tstkuber
#          image: DOCKER_USERNAME/tstkuber:latest
#          ports:
#            - containerPort: 3000
#---
#apiVersion: v1
#kind: Service
#metadata:
#  name: tstkuber-service
#spec:
#  selector:
#    app: tstkuber
#  ports:
#    - protocol: TCP
#      port: 80
#      targetPort: 3000
#      nodePort: 30080
#  type: NodePort
